version: "3"
services:
    db:
        image:  postgres
        restart: always
        ports:
            - "5430:5432"
        environment:
            POSTGRES_DATABASE: final-project
            POSTGRES_USER: final-project
            POSTGRES_PASSWORD: w3sgDLJyFC
